spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pfadb
    username: postgres
    password: nada1811
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


  mail:
    host: smtp.gmail.com

    port: 587
    username: elkhaldinada7@gmail.com
    password: sztc jkfu msmb scas
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
